da<-read.table("household_power_consumption.txt",sep=";",header=T)
da$Date1<-as.Date(da$Date,"%d/%m/%Y")
da1<-subset(da,Date1=="2007-02-01"|Date1=="2007-02-02")
da1$DateAndTime<-paste(da1$Date,da1$Time)
da1$DateAndTime<-strptime(da1$DateAndTime,"%d/%m/%Y %H:%M:%OS")
par(mfrow = c(2, 2))
with(da1, {plot(DateAndTime,Global_active_power,type="l",xlab="",ylab="Global Active Power (kilowatts)")
  plot(DateAndTime, Voltage, type="l",xlab="daytime",ylab="Voltage")
  {
    with(da1, plot(DateAndTime, Sub_metering_1, xlab="",ylab = "Energy sub metering", type = "n"))
    with(subset(da1), points(DateAndTime, Sub_metering_1, col = "black",type="l")) 
    with(subset(da1), points(DateAndTime, Sub_metering_2, col = "red",type="l")) 
    with(subset(da1), points(DateAndTime, Sub_metering_3, col = "blue",type="l")) 
    legend("topright",lty=1,col = c("black", "red","blue"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_1"))
    }
  plot(DateAndTime,Global_reactive_power, type="l",xlab="daytime",ylab="Global_reactive_power")
  })
dev.copy(png,file="plot4.png")
dev.off()